### ISSUE TITLE
Flickering when adjusting tooltip size/updating candidates

### ISSUE THREAD

**Issue by ianyepan** [tumashu/company-posframe#27]
First of all, thank you for this package -- I used vanilla company before, but it always messes up the line numbers display and fringes, and the posframe approach solves this completely!

Nevertheless, the responsiveness is not quite at the same level as vanilla company. During typing, the posframe **flickers quite a lot** to fit in new candidates or adjust the frame size, while vanilla company seems to be handling the tooltip much more efficiently without any flicker.

In terms of usability, I haven't experienced slowing-down while typing as mentioned in #17 , but rather mostly the **flickering** issue is my main concern.

For your reference, here's my simple configuration:
```emacs-lisp
(use-package company-posframe
  :custom
  (company-posframe-show-metadata nil)
  (company-posframe-show-indicator nil)
  :config
  (company-posframe-mode +1))
```

**Comment by dgutov** [comment]
What if you set `x-wait-for-event-timeout` to 0?

**Comment by dgutov** [comment]
@ianpan870102 What's your OS? Please include the value of `system-configuration-features` as well.

If you're on macOS is particular, though, you might want to try the most recent build from the master branch.

**Comment by ianyepan** [comment]
Hi @dgutov , thanks for getting back.
I was originally on macOS, and setting `x-wait-for-event-timeout` didn't help much of the issue, sadly.
I have since moved to Windows + WSL with X11 GUI, and company-posframe doesn't work properly in that environment, so I've switched to vanilla company as of now.

**Comment by dgutov** [comment]
I see.

FWIW, people report `MobaXTerm` working okay there: https://github.com/sebastiencs/company-box/issues/76

**Comment by ianyepan** [comment]
Cheers! I am using `VcXsrv` at the moment. I'll give `MobaXTerm` a try as well.

**Comment by Yevgnen** [comment]
I don't have flickering in `company-box` but in `company-posframe`. Did you fix this? @dgutov

**Comment by dgutov** [comment]
@Yevgnen Neither is my project, I was just helping to provide more info while also debugging child frame problems on emacs-devel.

#56 might be similar to your problem. I'm not sure why the author closed it.

**Comment by Yevgnen** [comment]
@dgutov I'm sorry, I @ed the wrong person... 😅 Thanks for pointing me there!

**Comment by tumashu** [comment]
@Yevgnen I think I have no way to find the reason of this problem at the moment, for I have no mac machine to test  :-\

**Comment by tumashu** [comment]
@ianyepan try the newest posframe and (setq company-tooltip-minimum-width 40), or a bigger value,  maybe useful.

**Comment by Yevgnen** [comment]
@tumashu Seems the issue has been fixed here, thank you!

**Comment by zhenhua-wang** [comment]
I can still experience flickering in pgtk built. Setting `pgtk-wait-for-event-timeout` to 0 solves the problem for me...
